# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_correct_answer',
            field=models.IntegerField(default=0),
        ),
    ]
