# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-16 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180412_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='session_id',
            field=models.CharField(default=b'0', max_length=200),
        ),
    ]
