# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_test_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='test',
            name='session_id',
        ),
    ]
