# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180418_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('user_answer', models.CharField(max_length=200)),
                ('right_answer', models.CharField(max_length=200)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Test')),
            ],
        ),
    ]
