# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_testinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='is_user_answered_right',
            field=models.BooleanField(default=False),
        ),
    ]
