# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_testinfo_is_user_answered_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='multi_answer',
            field=models.BooleanField(default=False),
        ),
    ]
