# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180525_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default=b'python', max_length=200),
        ),
    ]
