# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testinfo',
            old_name='test_id',
            new_name='test',
        ),
    ]
